config/routes.rb
Rails.application.routes.draw do
  # videos routes
  resources :videos do
    resources :comments
  end
  # users routes
  resources :line_users, :except => [:index, :destroy]
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # rooms routes
  resources :rooms
  get '/rooms/find/:id', to: 'rooms#find', as: :find_room  
  # payment routes
  get '/payment/confirmention/:video_id', to: 'payment#confirmention', as: :confirmention
  get '/payment/pay/:video_id', to: 'payment#pay', as: :pay
  # subscription agreement routes
  get '/subscription_agreement/confirmention', to: 'subscription_agreement#confirmention', as: :renewal_confirmention
  get '/subscription_agreement/renewal', to: 'subscription_agreement#renewal', as: :renewal
  get '/subscription_agreement/expired_notification', to: 'subscription_agreement#expired_notification', as: :expired_notification
  # supports routes
  get '/supports/terms', to: 'supports#terms'
  get '/supports/company', to: 'supports#company'
  get '/supports/contact', to: 'supports#contact'
  # root route
  root to: 'videos#top_page'
  # mounts
  mount ActionCable.server => '/cable'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/video.rb
class Video < ApplicationRecord
  has_one_attached :video
  has_many :comments, dependent: :destroy

  validates :team1_id, presence: true
  validates :team2_id, presence: true
  validates :location, presence: true
  validate :video_validation

  def register(params, user)
    self.attributes = params
    self.title = make_video_title(params[:team1_id], params[:team2_id])
    self.sport = "soccer"
    self.contributor_id = user
    self.save
  end

  private
  def make_video_title(team1_id,team2_id)
    team1 = Team.find_by(id:team1_id)
    team2 = Team.find_by(id:team2_id)
    if team1.nil? || team2.nil?
      "Notitle"
    else
      team1_name = Team.find_by(id:team1_id).name
      team2_name = Team.find_by(id:team2_id).name
      "#{team1_name}<br>VS<br>#{team2_name}"
    end
  end
  
  def video_validation
    if !video.attached?
      errors.add(:video, 'が選択されていません')
    elsif video.blob.byte_size > 10.gigabytes
      video.purge
      errors.add(:video, 'ファイルが大きすぎます。')
    elsif !video?
      video.purge
      errors.add(:video, 'ファイルが無効な形式です。')
    end
  end

  def video?
    %w[video/mp4 video/gif video/mov video/m4v video/quicktime].include?(video.blob.content_type)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, except: [:top_page]

  def top_page
    return render '/videos/beforelogin' unless user_signed_in?
    @video = Video.all.order(:created_at).first
    team_id = current_user.team_id
    @my_team = Team.find(team_id).name
    @videos = Video.where('team1_id=? or team2_id=?', team_id, team_id).all.order(:created_at)
  end
  def index
    team_id = current_user.team_id
    @my_team = Team.find(team_id).name
    @team_videos = Video.where('team1_id=? or team2_id=?', team_id, team_id).all.order(:date)
  end
  def show
    @video = Video.find(params[:id])
    @comment = @video.comments.new
    @comments = @video.comments.all.order(:created_at)
  end
  def new
    @video = Video.new
  end
  def create
    @video = Video.new
    if @video.register(video_params, current_user.id)
      redirect_to videos_path
    else
      render 'new'
    end
  end
  private
    def video_params
      params.require(:video).permit(:video, :team1_id, :team2_id, :date, :location)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_thumbnail.html.erb
<div class="img-thumbnail thumbnail">
  <%= image_tag("video_thumbnail.png", class:"rounded img-fluid") %><br>
  <div class="info text-center mx-auto" style="width: 100%;">
    <h5><%= title.html_safe %></h5>
    <small><%= date.strftime("%Y年%m月%d日") %></small><br>
    <small><%= location %></small>
  </div>
</div>

app/views/videos/beforelogin.html.erb
<%= stylesheet_link_tag "top_page", :media => "all" %>
<div class="spocom_top bg-white text-center">
  <br>
  <%= image_tag("spocom_logo.png", class:"img-fluid w-50 my-5") %>

  <h1 class="my-3">もっと本気で、<br>
  もっと楽しく。</h1>

  <div class="button pt-3 pb-5">
    <%= link_to "会員登録", new_user_registration_path, class:"btn btn-primary btn-lg mx-2" %>
    <%= link_to "ログイン", new_user_session_path, class:"btn btn-primary btn-lg mx-2" %>
  </div>

  <h2 class="text-white mt-5">spocom とは</h2>
    <%= image_tag("whatspocom.png", class:"img-fluid") %>

  <h2 class="text-white mt-5">使い方</h2>
    <%= image_tag("whatspocom.png", class:"img-fluid") %>

  <div class="spocom_feature">
    <br>
    <h3 class="text-white my-3">TODAY'S GAME</h3>
      <p>その日の試合が見れる。</p>
      <div class="image clearfix my-2">
        <%= image_tag("video.png") %>
      </div>
    <h3 class="text-white my-3">GOOD PLAY</h3>
      <p>ライバルのいいプレーを見て学ぶ。</p>
      <div class="image clearfix my-2">
        <%= image_tag("video.png") %>
      </div>
    <h3 class="text-white my-3">CHAT</h3>
      <p>監督やコーチに直接質問できる。</p>
      <div class="image clearfix my-2">
        <%= image_tag("video.png") %>
      </div>
      <br>
  </div>

  <div class="cta my-3 mt-5">
    <p class="my-3">spocom をはじめる</p>
    <div class="button py-3">
      <%= link_to "会員登録", new_user_registration_path, class:"btn btn-primary btn-lg mx-2" %>
      <%= link_to "ログイン", new_user_session_path, class:"btn btn-primary btn-lg mx-2" %>
    </div>
    <br><br>
  </div>
</div>

app/views/videos/index.html.erb
<h5 class="heading">MY GAMES</h5>
<br>
<h5 class="team-heading"><%= "#{@my_team}の動画" %></h5>
<div class="container">
  <% @team_videos.each do |video| %>
      <%= link_to video_path(video) do %>
        <%= render partial:'/videos/thumbnail', locals:{title:video.title, date:video.date, location:video.location} %>
      <% end %>
      <br>
  <% end %>
</div>

app/views/videos/new.html.erb
<h5 class="heading">動画アップロード画面</h5>

<div class="container">
  <%= form_error_messages(@video) %>

  <%= form_with(model: @video, local: true) do |form| %>

    <div class="form-group text-center">
      <label for="video_video" class="upload-btn"><br>動画を選択<br><br></label>
      <%= form.file_field :video, direct_upload: true,  class: "hidden" %>
    </div>

    <div class="form-group">
      <%= form.label :team1_id %>
      <%= form.collection_select :team1_id, Team.all, :id, :name, {:prompt => "選択してください"}, {class:"form-control"} %>
    </div>

    <div class="form-group">
      <%= form.label :team2_id %>
      <%= form.collection_select :team2_id, Team.all, :id, :name, {:prompt => "選択してください"}, {class:"form-control"} %>
    </div>

    <div class="form-group">
      <%= form.label :location %><br>
      <%= form.text_field :location, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :date %><br>
      <%= form.date_select :date ,{use_month_numbers: true}, {class:"form-control select-date"} %>
    </div>

    <div class="text-center">
      <%= form.submit("アップロード", class: "btn btn-primary btn-lg") %>
    </div>

  <% end %>
  <br>
</div>

app/views/videos/show.html.erb
<h5 class="heading"><%= image_tag "check_sheet_icon.png", width:30, class:'img-fluid'; %>TEAM VIDEO</h5>
<div class=container>
  <div class="electric_bulletin_board row">
    <div class="offset-2">
      <%= video_tag(rails_blob_path(@video.video), controls:true, disposition:'inline', class:'img-fluid video') %>
    </div>
  </div>
  <div class="audience_seats pt-3">
    <div class="comment">
      <div class="list-group small">
        <li class="list-group-item header">動画コメント</li>
        <%= form_with(model:[@video, @comment], local: true) do |form| %>
          <li class="list-group-item list-group-item-action add-comment">コメントを追加する...</li>
          <li class="list-group-item hidden comment-form">
            <div class="row ml-0 mr-0 form-group">
              <%= form.text_field :body, class:"form-control col-9" %>
              <%= form.text_field :time, class:"form-control col-3" %>
            </div>
            <%= form.submit "コメントの投稿", class:"btn-primary btn-block"%>
          </li>
        <% end %>

        <% @comments.each do |cmt| %>
          <li class="list-group-item">
            <div class="row m-0">
              <div class="col-9"><%= cmt.body %></div><div class="col-3 text-center">[<%= cmt.time %>]</div>
            </div>
          </li>
        <% end %>
      </div>
    </div>
      <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  </div>
</div>

app/views/videos/topPage.html.erb
<ul>
<li><%= link_to "新規登録", new_user_registration_path %></li>
<li><%= link_to "ログイン", new_user_session_path %></li>
<li><%= link_to "ログアウト", destroy_user_session_path %></li>

<li><%= link_to "動画一覧",videos_path %></li>
<li><%= link_to "動画アップロード", new_video_path %></li>
</ul>

app/views/videos/top_page.html.erb
<%= stylesheet_link_tag "top_page", :media => "all" %>
<div class="todays_game">

  <div class="todays_game_title mt-2">
    <div class="gray_line"></div>
    <div class="light_gray_line"></div>
    <h1 class="text-center py-2"><p class="mb-0"><span class="fa fa-check"></span>&nbsp;TODAY'S GAME</p></h1>
  </div>

  <div class="todays_video pt-3">
    <div class="mx-auto" style="width: 300px;">
      <% if @videos.present? %>
        <% @videos.last(1).each do |video| %>
          <%= link_to video_path(video) do %>
            <%= render partial:'/videos/thumbnail', locals:{title:video.title, date:video.date, location:video.location} %>
          <% end %>
          <div class="video_title text-center mt-4 mb-1 w-75 mx-auto">
            <%= video.title.html_safe %>
          </div>
        <% end %>
      <% end%>
    </div>

    <div class="gray_line"></div>
    <div class="gray_line"></div>

  </div>
</div>

<div class="good_play text-center mt-4">
  <h2 class="px-5"><p class="m-0"><span class="fa fa-trophy"></span> GOOD PLAY</p></h2>
  <div class="image clearfix my-2">
    <%= image_tag("video.png") %>
  </div>
  <div class="image clearfix my-2">
    <%= image_tag("video.png") %>
  </div>  
  <div class="image clearfix my-2">
    <%= image_tag("video.png") %>
  </div>
</div>