config/routes.rb
Rails.application.routes.draw do
  # videos routes
  resources :videos do
    resources :comments
  end
  # users routes
  resources :line_users, :except => [:index, :destroy]
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # rooms routes
  resources :rooms
  get '/rooms/find/:id', to: 'rooms#find', as: :find_room  
  # payment routes
  get '/payment/confirmention/:video_id', to: 'payment#confirmention', as: :confirmention
  get '/payment/pay/:video_id', to: 'payment#pay', as: :pay
  # subscription agreement routes
  get '/subscription_agreement/confirmention', to: 'subscription_agreement#confirmention', as: :renewal_confirmention
  get '/subscription_agreement/renewal', to: 'subscription_agreement#renewal', as: :renewal
  get '/subscription_agreement/expired_notification', to: 'subscription_agreement#expired_notification', as: :expired_notification
  # supports routes
  get '/supports/terms', to: 'supports#terms'
  get '/supports/company', to: 'supports#company'
  get '/supports/contact', to: 'supports#contact'
  # root route
  root to: 'videos#top_page'
  # mounts
  mount ActionCable.server => '/cable'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :user_rooms
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    if current_user.coach?
      @team_users = User.where("team_id = ?", current_user.team_id)
                        .where.not(id: current_user.id).all()
      @list_name = "選手一覧"
    else
      @team_users = User.where("team_id = ?", current_user.team_id)
                        .where("position = ?", 2).all()
      @list_name = "監督一覧"
    end
  end

  def find
    if current_user.teammate?(params[:id])
      room_id = UserRoom.find_room_id(current_user.id, params[:id])
      if room_id.blank?
        create_room(params[:id])
      else
        redirect_to room_path(room_id)
      end
    else
      render partial:"/error/404"
    end
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages
    to_user = @room.user_rooms.where("user_id!=?", current_user.id).first.user_id
    to_user = User.find_by(id: to_user)
    if to_user.nil?
      @to_user_name = "UNKNOWN"
    else
      @to_user_name = to_user.fullname
    end
  end

  private
  def create_room(to_user_id)
    new_room = Room.create()
    user_room = UserRoom.create(room_id: new_room.id, user_id: current_user.id)
    to_user_room = UserRoom.create(room_id: new_room.id, user_id: to_user_id)
    redirect_to room_path(new_room.id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def get_user_info_by_id(id)
    user = User.find_by(id:id)
    if user.present?
      {icon:image_tag(user.image, width:100), fullname:user.fullname}
    else
      {icon:nil, fullname:nil}
    end
  end

  def last_message(id)
    room_id = UserRoom.find_room_id(current_user.id, id)
    if room_id.present?
      message = Room.find(room_id).messages.last
      if message.present?
        message.content
      end
    end
  end
end

app/views/rooms/index.html.erb
<h5 class="heading">CHAT</h5>

<div class="container">
  <div class="media">
    <%= image_tag(current_user.image, width:80, class:"mr-3 rounded-circle") %>
    <div class="media-body">
      <h5 class="mt-1"><%= current_user.fullname %></h5>
    </div>
  </div>
  <hr><small><%= @list_name %></small><hr>
  <% @team_users.each do |team_user| %>
    <div class="">
      <%= link_to find_room_path(team_user), class:"" do %>
        <div class="media">
          <%= image_tag(team_user.image, width:70, class:"mr-3 rounded-circle") %>
          <div class="media-body">
            <h5 class="mt-1"><%= team_user.fullname %></h5>
            <p class="mb-0 text-truncate" style="max-width:250px;"><%= last_message(team_user.id) %></p>
          </div>
        </div>
      <% end %>
      <hr>
    </div>
  <% end %>
</div>

app/views/rooms/show.html.erb
<h5 class="heading"><%= @to_user_name %></h5>

<div class="container-fluid chat-room">
  <div id="messages" data-room_id="<%= @room.id %>">
    <%= render @messages %>
  </div>
  <div class="form-inline chat-form fixed-bottom">
    <textarea class="form-control" data-behavior="room_speaker"></textarea>
    <button type="submit" class="submit-btn btn btn-primary">送信</button>
  </div>
</div>
<script>
  setTimeout(function() {
    window.scroll(0,$(document).height());
  }, 0);

  $(function() {
    var $textarea = $('[data-behavior~=room_speaker]');
    var lineHeight = parseInt($textarea.css('lineHeight'));
    $textarea.on('input', function(e) {
      var lines = ($(this).val() + '\n').match(/\n/g).length;
      $(this).height(lineHeight * lines);
    });
  });
</script>