config/routes.rb
Rails.application.routes.draw do
  # videos routes
  resources :videos do
    resources :comments
  end
  # users routes
  resources :line_users, :except => [:index, :destroy]
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # rooms routes
  resources :rooms
  get '/rooms/find/:id', to: 'rooms#find', as: :find_room  
  # payment routes
  get '/payment/confirmention/:video_id', to: 'payment#confirmention', as: :confirmention
  get '/payment/pay/:video_id', to: 'payment#pay', as: :pay
  # subscription agreement routes
  get '/subscription_agreement/confirmention', to: 'subscription_agreement#confirmention', as: :renewal_confirmention
  get '/subscription_agreement/renewal', to: 'subscription_agreement#renewal', as: :renewal
  get '/subscription_agreement/expired_notification', to: 'subscription_agreement#expired_notification', as: :expired_notification
  # supports routes
  get '/supports/terms', to: 'supports#terms'
  get '/supports/company', to: 'supports#company'
  get '/supports/contact', to: 'supports#contact'
  # root route
  root to: 'videos#top_page'
  # mounts
  mount ActionCable.server => '/cable'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/controllers/line_users_controller.rb
class LineUsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  def new
    @new_user = User.new()
    @omniauth = line_params
  end
  
  def create
    @omniauth = line_params
    @new_user = User.new(user_params)
    @new_user.attributes = {provider: @omniauth[:provider], uid: @omniauth[:uid], password: Devise.friendly_token[0, 20]}
    if @new_user.save
      @new_user.set_values(@omniauth)
      sign_in(:user, @new_user)
      flash[:notice] = "ログインしました"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if current_user == @user
      if @user.update(user_params)
        redirect_to root_path
      else
        render 'edit'
      end
    else
      render partial:'error/404'
    end
  end

  private
  def user_params
    params.require(:user).permit(:last_name, :kana_last_name, :first_name, :kana_first_name, 
                                 :team_id, :email, :image, :agreement)
  end
  def line_params
    params.require(:line).permit(:provider, :uid, 
                                 credentials: [:expires, :expires_at, :refresh_token, :token, :secret], 
                                 info: [:description, :image, :name])
  end
end

app/helpers/line_users_helper.rb
module LineUsersHelper
end

app/views/line_users/edit.html.erb
<h5 class="heading">編集画面</h5>

<div class="container">
  <%= form_error_messages(@user) %>

  <%= form_with(model: @user, url:  line_user_path(@user), local: true) do |form| %>

    <div class="form-group row">
      <div class="col-3">
        <%= form.label :name %>
      </div>
      <div class="offset-2 col-10">
        <%= form.label :last_name %><%= form.text_field :last_name, class:"form-control"%>
        <%= form.label :first_name %><%= form.text_field :first_name, class:"form-control"%>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-3">
        <%= form.label :kana_name %>
      </div>
      <div class="offset-2 col-10">
        <%= form.label :kana_last_name %><%= form.text_field :kana_last_name, class:"form-control" %>
        <%= form.label :kana_first_name %><%= form.text_field :kana_first_name, class:"form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :team_id %>
      <%= form.collection_select :team_id, Team.all, :id, :name, {:prompt => "選択してください"},{class:"form-control"} %>
    </div>

    <div class="form-group">
      <%= form.label :image %><br>
      <%= form.file_field :image, direct_upload: true, class:"form-control-file" %><br>
    </div>

    <div class="form-group text-center">
      <%= form.submit("変更", class: "btn-primary btn-lg") %>
    </div>

  <% end %>
  <br>
</div>

app/views/line_users/new.html.erb
<h4 class="before-login-heading">会員登録</h4>

<div class="container">
  <%= form_error_messages(@new_user) %>
  
  <%= form_with(model: @new_user, url: line_users_path(line: @omniauth), local: true) do |form| %>

    <div class="form-group row">
      <div class="col-3">
        <%= form.label :name %>
      </div>
      <div class="offset-2 col-10">
        <%= form.label :last_name %><%= form.text_field :last_name, class:"form-control"%>
        <%= form.label :first_name %><%= form.text_field :first_name, class:"form-control"%>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-3">
        <%= form.label :kana_name %>
      </div>
      <div class="offset-2 col-10">
        <%= form.label :kana_last_name %><%= form.text_field :kana_last_name, class:"form-control" %>
        <%= form.label :kana_first_name %><%= form.text_field :kana_first_name, class:"form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :team_id %>
      <%= form.collection_select :team_id, Team.all, :id, :name, {:prompt => "選択してください"},{class:"form-control"} %>
    </div>

    <div class="form-group">
      <%= form.label :image %><br>
      <%= form.file_field :image, direct_upload: true, class:"form-control-file" %><br>
    </div>

    <div class="form-group">
      <div class="form-check">
        <%= f.check_box :agreement, :as => :boolean, checked:false %>
        <label class="form-check-label" for="user_agreement">
          <p>利用規約とプライバシーポリシーに同意</p>
        </label>
      </div>
      <div class="terms">
        <%= render partial:'/supports/terms' %>
      </div>
    </div>

    <div class="form-group text-center">
      <%= form.submit("登録", class: "btn-primary btn-lg") %>
    </div>

  <% end %>
  <br>
</div>