config/routes.rb
Rails.application.routes.draw do
  # videos routes
  resources :videos do
    resources :comments
  end
  # users routes
  resources :line_users, :except => [:index, :destroy]
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # rooms routes
  resources :rooms
  get '/rooms/find/:id', to: 'rooms#find', as: :find_room  
  # payment routes
  get '/payment/confirmention/:video_id', to: 'payment#confirmention', as: :confirmention
  get '/payment/pay/:video_id', to: 'payment#pay', as: :pay
  # subscription agreement routes
  get '/subscription_agreement/confirmention', to: 'subscription_agreement#confirmention', as: :renewal_confirmention
  get '/subscription_agreement/renewal', to: 'subscription_agreement#renewal', as: :renewal
  get '/subscription_agreement/expired_notification', to: 'subscription_agreement#expired_notification', as: :expired_notification
  # supports routes
  get '/supports/terms', to: 'supports#terms'
  get '/supports/company', to: 'supports#company'
  get '/supports/contact', to: 'supports#contact'
  # root route
  root to: 'videos#top_page'
  # mounts
  mount ActionCable.server => '/cable'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom">
  <nav class="navbar navbar-dark bg-dark p-2">
    <ul class="nav nav-justified">
      <li class="text-center">
        <%= link_to root_path do %><i class="fa fa-home fa-3x"  style="color:white"></i><% end %>
      </li>
      <li class="text-center">
        <%= link_to videos_path do %><i class="fa fa-play-circle fa-3x" style="color:white"></i><% end %>
      </li>
      <li class="text-center">
        <%= link_to rooms_path do %><i class="fa fa-comments fa-3x" style="color:white"></i><% end %>
      </li>
      <li class="text-center">
        <%= link_to new_video_path do %><i class="fa fa-upload fa-3x" style="color:white"></i><% end %>
      </li>
    </ul>
  </nav>
</footer><!--footer end-->

app/views/layouts/_header.html.erb
<header class="head-main">
  <div class="navbar navbar-dark bg-dark box-shadow p-1">
    <div class="container d-flex justify-content-between p-0">
      <div class="nav-button ml-0"><span id="nav-icon3"><span></span><span></span><span></span><span></span></span></div>
      <div class="navbar-brand d-flex p-0 mx-auto">
        <%= link_to image_tag("naver.png", :height=> 40, :alt => "アイコン"), root_path %>
      </div>
    </div>
  </div> <!--navbar end-->
  <div class="fixed-top main-menu">
    <div class="media">
      <%= image_tag(current_user.image, width:70, class:"mr-3 rounded-circle") %>
      <div class="media-body">
        <h5 class="mt-0 text-light"><%= current_user.fullname + "さん" %></h5>
        <%= link_to "　マイページへ　", edit_line_user_path(current_user), class:"btn btn-info" %>
      </div>
    </div>
    <div class="flex p-5">
      <ul class="nav flex-column">
        <li class="nav-item delay-1">
          <i class="fa fa-caret-right fa-2x text-primary align-middle"></i>
          <%= link_to "お問い合わせ", supports_contact_path %>
        </li>
        <li class="nav-item delay-2">
          <i class="fa fa-caret-right fa-2x text-primary align-middle"></i>
          <%= link_to "運営会社", supports_company_path %>
        </li>
        <li class="nav-item delay-3">
          <i class="fa fa-caret-right fa-2x text-primary align-middle"></i>
          <%= link_to "利用規約", supports_terms_path %>
        </li>
        <li class="nav-item delay-4">
          <i class="fa fa-caret-right fa-2x text-primary align-middle">
          </i><%= link_to "ログアウト", destroy_user_session_path %>
        </li>
      </ul>
    </div>
  </div> <!--main-menu end-->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spocom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <% if user_signed_in? %>
      <%= render '/layouts/header' %>
      <div id="wrapper"><%= yield %></div>
      <%= render '/layouts/footer' %>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>